name: build_package

run-name: build

on: [push]

jobs:
  build:
    name: build
    runs-on: macOS-latest
    steps:
        - run:
            ls -al
            xcodebuild -xcodeproj RichEditorSwiftUI/Package.swift -scheme "RichEditorSwiftUI" clean archive -sdk iphoneos
